import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.DateTimeField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;
import com.vaadin.ui.ComboBox;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements view { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Tagebuch extends HorizontalLayout {
    protected DateTimeField datePicker;
    protected VerticalLayout verticalLayout;
    protected ComboBox<java.lang.String> symptomBox;
    protected Image goodSmiley;
    protected Image middleSmiley;
    protected Image badSmiley;
    protected Label goodlabel;
    protected Label middlelabel;
    protected Label badlabel;
    protected Button saveButton;
    protected Label moodLabel;
    protected Grid<de.tud.Model.DataModelDiary> table;

    public Tagebuch() {
        Design.read(this);
    }
}
