package de.tud.View;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design.*;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Tagebuch2 extends HorizontalLayout {
    protected DateTimeField datePicker;
    protected VerticalLayout verticalLayout;
    protected Image goodSmiley;
    protected Image middleSmiley;
    protected Image badSmiley;
    protected Label goodlabel;
    protected Label middleLabel;
    protected Label badLabel;
    protected Button saveButton;
    protected Grid<de.tud.Model.DataModelDiary> table;
    protected ComboBox symptomBox;

    public Tagebuch2() {
        Design.read(this);
    }
}
