package de.tud.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.DateTimeField;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;
import de.tud.model.DiaryEntryTableViewAdapter;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements view { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Tagebuch extends HorizontalLayout {
    protected DateTimeField datePicker;
    protected VerticalLayout verticalLayout;
    protected Image goodSmiley;
    protected Image middleSmiley;
    protected Image badSmiley;
    protected Label goodlabel;
    protected Label middleLabel;
    protected Label badLabel;
    protected Button saveButton;
    protected Grid<DiaryEntryTableViewAdapter> table;

    public Tagebuch() {
        Design.read(this);
    }
}
