package de.tud.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.Panel;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import org.vaadin.risto.stepper.FloatStepper;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.DateTimeField;
import com.vaadin.ui.NativeButton;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class VitalDataUIDesigner extends Panel {
    protected FormLayout form;
    protected Label captionLabel;
    protected DateTimeField dataPicker;
    protected NativeButton saveVitalData;
    protected HorizontalLayout weight;
    protected Image weightPicture;
    protected Label weightLabel;
    protected FloatStepper weightStepper;
    protected HorizontalLayout height;
    protected Image heightPicture;
    protected Label heightLabel;
    protected FloatStepper heightStepper;
    protected HorizontalLayout bloodPressure;
    protected Image bloodPressurePicture;
    protected Label bloodPressureLabel;
    protected FloatStepper bloodPressureStepper1;
    protected HorizontalLayout bloodPressure11;
    protected Image bloodPressurePicture11;
    protected Label bloodPressureLabel11;
    protected FloatStepper bloodPressureStepper11;
    protected HorizontalLayout heartRate;
    protected Image heartRatePicture;
    protected Label heartRateLabel;
    protected FloatStepper heartRateStepper;


    public VitalDataUIDesigner() {
        Design.read(this);
    }
}
