package de.tud.view.Welfare;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.DateTimeField;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.RadioButtonGroup;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class WelfareDesigner extends Panel {
    protected Label captionLabel;
    protected HorizontalLayout concentration;
    protected Image concentrationPicture;
    protected Label concentrationLabel;
    protected RadioButtonGroup<String> concentrationRadioButton;
    protected Image concentrationRadiobuttonPicture;
    protected HorizontalLayout fitnesslay;
    protected Image fitnessPicture;
    protected Label fitnessLabel;
    protected RadioButtonGroup<String> fitnessRadioButton;
    protected Image fitnessRadiobuttonPicture;
    protected HorizontalLayout sleep;
    protected Image sleepPicture;
    protected Label sleepLabel;
    protected RadioButtonGroup<String> sleepRadioButton;
    protected Image sleepRadiobuttonPicture;
    protected DateTimeField dataPicker;
    protected NativeButton save;


    public WelfareDesigner() {
        Design.read(this);
    }
}
