package de.tud.view.Welfare;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.DateTimeField;
import com.vaadin.ui.NativeButton;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class WelfareDesigner extends Panel {
    protected HorizontalLayout concentration;
    protected Image concentrationPicture;
    protected Label concentrationLabel;
    protected HorizontalLayout concentrationSmileys;
    protected Image goodSmiley;
    protected Image middleSmiley;
    protected Image badSmiley;
    protected HorizontalLayout fitness;
    protected Image fitnessPicture;
    protected Label fitnessLabel;
    protected HorizontalLayout fitnessSmileys;
    protected Image goodSmiley1;
    protected Image middleSmiley1;
    protected Image badSmiley1;
    protected HorizontalLayout sleep;
    protected Image sleepPicture;
    protected Label sleepLabel;
    protected HorizontalLayout sleepSmileys;
    protected Image goodSmiley2;
    protected Image middleSmiley2;
    protected Image badSmiley2;
    protected DateTimeField dataPicker;
    protected NativeButton save;


    public WelfareDesigner() {
        Design.read(this);
    }
}
