package de.tud.view.Homework;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;

import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.DateField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Label;


/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class HomeworkDesigner extends VerticalLayout {
    protected ComboBox<String> combobox;
    protected DateField dataPicker;
    protected ComboBox<String> repeatBox;
    protected Button saveButton;
    protected TextField homeworkName;
    protected TextArea homeworkDescription;
    protected Label calenderLabel;
    protected HomeworkCalender calendar;


    public HomeworkDesigner() {
        Design.read(this);
    }


}
